### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ghost** [128technology/lte-tools#2]
I tried to use this but encountered `TypeError: 'NoneType' object is not subscriptable` - which is obviously a Python error. The full steps I took to reproduce this issue are below. It appears that perhaps the problem is that the Python script is trying to run a pCLI command and nothing is being returned (hence `NoneType`) - this feels like either:
- a pCLI auth or access problem
- a Bug
- a Compatibility problem (this environment is v6.1.5)

Steps to reproduce this issue:
- Tested SNMP walk before changes. Everything worked fine.
- Followed steps in the README:
- cloned repo on conductor
- added test router to top.sls
- triggered salt run (no errors)
- Found that SNMP walk no longer works
- Logged on to the test router
- Found that /etc/snmp/conf.d/ was empty and so the include was failing and snmpd would not start
- Duplicated 128T-snmpd.conf, 128T-snmpd-lte.conf, snmpd.conf, snmptrapd.conf to /etc/snmp/conf.d manually
- Now snmpd starts okay, and SNMP walk works fine again.
- However:
`[chris@jumpbox ~]$ snmpget -v2c -c <REMOVED> thecpe 1.3.6.1.4.1.45956.1.100
SNMPv2-SMI::enterprises.45956.1.100 = No Such Instance currently exists at this OID`
- Tried running the python script manually on the test router.
- However:
`[root@thecpe snmp]# /usr/sbin/snmp_lte_stats.py 1.3.6.1.4.1.45956.1.100
Traceback (most recent call last):
  File "/usr/sbin/snmp_lte_stats.py", line 206, in <module>
    objects = populate_objects()
  File "/usr/sbin/snmp_lte_stats.py", line 177, in populate_objects
    stats = lte_stats(api)
  File "/usr/sbin/snmp_lte_stats.py", line 161, in lte_stats
    return request.json()['data']['allRouters']['nodes'][0]['nodes']['nodes'][0]['deviceInterfaces']['nodes'][0]['networkInterfaces']['nodes'][0]['deviceInterface']['state']['networkPluginState']['LTE']
TypeError: 'NoneType' object is not subscriptable
[root@thecpe snmp]# /usr/sbin/snmp_lte_stats.py 1.3.6.1.4.1.45956.1
Traceback (most recent call last):
  File "/usr/sbin/snmp_lte_stats.py", line 206, in <module>
    objects = populate_objects()
  File "/usr/sbin/snmp_lte_stats.py", line 177, in populate_objects
    stats = lte_stats(api)
  File "/usr/sbin/snmp_lte_stats.py", line 161, in lte_stats
    return request.json()['data']['allRouters']['nodes'][0]['nodes']['nodes'][0]['deviceInterfaces']['nodes'][0]['networkInterfaces']['nodes'][0]['deviceInterface']['state']['networkPluginState']['LTE']
TypeError: 'NoneType' object is not subscriptable`

**Comment by ghost** [comment]
Is this repo owned/maintained?

**Comment by majes-git** [comment]
Hi @chris-tomkins-flexgrid,

Could you please share your SSR config? Based on the output above it looks like you don't have a device-interface called "LTE" on your router.

Yes, you right - there could be better exception handling. The code was build for a specific environment, where devices etc. were properly named.

Best Regards,
Mathias

**Comment by ghost** [comment]
Sure Mathias, thanks. Here is the anonymised config (ignore the fact the grep doesn't appear to match the output... it's due to me anonymising it):
[anon-config.txt](https://github.com/128technology/lte-tools/files/13649781/anon-config.txt)

**Comment by ghost** [comment]
Any more thoughts on this?
